### ISSUE TITLE
Проблема с фильтрами "Некорректный запрос: ..."

### ISSUE THREAD

**Issue by YudovAlexei** [amocrm/amocrm-api-php#34]
В чем проблема?

Исключение:
**AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны**

Проблемный код:

```

$contactsFilterModel = new ContactsFilter();

$testFilterCustomFieldsValues = [
  40335 => 'Some Position'
];

$contactsFilterModel->setCustomFieldsValues($testFilterCustomFieldsValues);

try {
  $apiClient->contacts()->get($contactsFilterModel);
} catch ( AmoCRMApiException $e ) {
  var_dump($e);
}
```

**Comment by bessudnov** [comment]
А можете подробности по запросу предоставить?

Получить можно таким образом
```
try {
    $apiClient->contacts()->get($contactsFilterModel);
} catch (AmoCRMApiException $e) {
    var_dump($e->getLastRequestInfo());
}
```

**Comment by YudovAlexei** [comment]
```
object(AmoCRM\Exceptions\AmoCRMoAuthApiException)#134 (11) {
  ["errorCode":protected]=>
  int(0)
  ["description":protected]=>
  string(0) ""
  ["title":protected]=>
  string(2068) "AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны in \vendor\amocrm\oauth2-amocrm\src\AmoCRMException.php:24
Stack trace:
#0 \vendor\amocrm\oauth2-amocrm\src\AmoCRM.php(135): AmoCRM\OAuth2\Client\Provider\AmoCRMException::errorResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 \vendor\league\oauth2-client\src\Provider\AbstractProvider.php(628): AmoCRM\OAuth2\Client\Provider\AmoCRM->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#2 \vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#3 \vendor\amocrm\amocrm-api-library\src\AmoCRM\OAuth\AmoCRMOAuth.php(130): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#4 \vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php(115): AmoCRM\OAuth\AmoCRMOAuth->getAccessTokenByRefreshToken(Object(League\OAuth2\Client\Token\AccessToken))
#5 \vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php(367): AmoCRM\Client\AmoCRMApiRequest->refreshAccessToken()
#6 \vendor\amocrm\amocrm-api-library\src\AmoCRM\EntitiesServices\BaseEntity.php(87): AmoCRM\Client\AmoCRMApiRequest->get('api/v4/contacts', Array)
#7 \index.php(137): AmoCRM\EntitiesServices\BaseEntity->get(Object(AmoCRM\Filters\ContactsFilter))
#8 {main}"
  ["lastRequestInfo":protected]=>
  array(0) {
  }
  ["message":protected]=>
  string(2068) "AmoCRM\OAuth2\Client\Provider\AmoCRMException: Некорректный запрос: В запросе отсутствует ряд параметров или параметры невалидны in \vendor\amocrm\oauth2-amocrm\src\AmoCRMException.php:24
Stack trace:
#0 \vendor\amocrm\oauth2-amocrm\src\AmoCRM.php(135): AmoCRM\OAuth2\Client\Provider\AmoCRMException::errorResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 \vendor\league\oauth2-client\src\Provider\AbstractProvider.php(628): AmoCRM\OAuth2\Client\Provider\AmoCRM->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#2 \vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#3 \vendor\amocrm\amocrm-api-library\src\AmoCRM\OAuth\AmoCRMOAuth.php(130): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#4 \vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php(115): AmoCRM\OAuth\AmoCRMOAuth->getAccessTokenByRefreshToken(Object(League\OAuth2\Client\Token\AccessToken))
#5 \vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php(367): AmoCRM\Client\AmoCRMApiRequest->refreshAccessToken()
#6 \vendor\amocrm\amocrm-api-library\src\AmoCRM\EntitiesServices\BaseEntity.php(87): AmoCRM\Client\AmoCRMApiRequest->get('api/v4/contacts', Array)
#7 \index.php(137): AmoCRM\EntitiesServices\BaseEntity->get(Object(AmoCRM\Filters\ContactsFilter))
#8 {main}"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(126) "\vendor\amocrm\amocrm-api-library\src\AmoCRM\OAuth\AmoCRMOAuth.php"
  ["line":protected]=>
  int(133)
  ["trace":"Exception":private]=>
  array(4) {
    [0]=>
    array(6) {
      ["file"]=>
      string(132) "\vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php"
      ["line"]=>
      int(115)
      ["function"]=>
      string(28) "getAccessTokenByRefreshToken"
      ["class"]=>
      string(24) "AmoCRM\OAuth\AmoCRMOAuth"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(League\OAuth2\Client\Token\AccessToken)#27 (5) {
          ["accessToken":protected]=>
          string(870) "removed"
          ["expires":protected]=>
          int(1592895662)
          ["refreshToken":protected]=>
          string(872) "removed"
          ["resourceOwnerId":protected]=>
          NULL
          ["values":protected]=>
          array(1) {
            ["token_type"]=>
            string(6) "Bearer"
          }
        }
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(132) "\vendor\amocrm\amocrm-api-library\src\AmoCRM\Client\AmoCRMApiRequest.php"
      ["line"]=>
      int(367)
      ["function"]=>
      string(18) "refreshAccessToken"
      ["class"]=>
      string(30) "AmoCRM\Client\AmoCRMApiRequest"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(136) "\vendor\amocrm\amocrm-api-library\src\AmoCRM\EntitiesServices\BaseEntity.php"
      ["line"]=>
      int(87)
      ["function"]=>
      string(3) "get"
      ["class"]=>
      string(30) "AmoCRM\Client\AmoCRMApiRequest"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        string(15) "api/v4/contacts"
        [1]=>
        array(3) {
          ["filter"]=>
          array(1) {
            ["custom_fields_values"]=>
            array(1) {
              [40335]=>
              string(13) "Some Position"
            }
          }
          ["limit"]=>
          int(50)
          ["page"]=>
          int(1)
        }
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(65) "\index.php"
      ["line"]=>
      int(137)
      ["function"]=>
      string(3) "get"
      ["class"]=>
      string(34) "AmoCRM\EntitiesServices\BaseEntity"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(AmoCRM\Filters\ContactsFilter)#112 (14) {
          ["ids":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["names":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["createdBy":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["updatedBy":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["responsibleUserId":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["createdAt":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["updatedAt":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["closestTaskAt":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["customFieldsValues":"AmoCRM\Filters\ContactsFilter":private]=>
          array(1) {
            [40335]=>
            string(13) "Some Position"
          }
          ["query":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["orderField":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["direction":"AmoCRM\Filters\ContactsFilter":private]=>
          NULL
          ["page":"AmoCRM\Filters\ContactsFilter":private]=>
          int(1)
          ["limit":"AmoCRM\Filters\ContactsFilter":private]=>
          int(50)
        }
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}
```

**Comment by YudovAlexei** [comment]
> А можете подробности по запросу предоставить?
> 
> Получить можно таким образом
> 
> ```
> try {
>     $apiClient->contacts()->get($contactsFilterModel);
> } catch (AmoCRMApiException $e) {
>     var_dump($e->getLastRequestInfo());
> }
> ```

Приложил подробный результат запроса

**Comment by YudovAlexei** [comment]
Такая ошибка может появиться из-за Alpha версии фильтров, мой amocrm аккаунт не подключен к закрытому тестированию?
``
Функционал фильтрации находится в альфа-версии и пока что доступен ограниченному списку аккаунтов.
``
[Фильтрация(Alpha)](https://www.amocrm.ru/developers/content/crm_platform/filters-api#common-info)

**Comment by YudovAlexei** [comment]
Вообщем разобрался, когда токен обновил. Плохо что исключение на счет истекшего токена такое не точное.

**Comment by salesevolution** [comment]
> Плохо что исключение на счет истекшего токена такое не точное.

Пахнет новым issue и подробностями с предполагаемым решением
