### ISSUE TITLE
Проблемы с EventsFilter и setValueAfter. Ребят помогите.

### ISSUE THREAD

**Issue by veed007** [amocrm/amocrm-api-php#356]
Мой код:
function GetEvents($apiClient)
{
    $s = '[{"lead_status":{"id":22410637,"pipeline_id":1434445}}]';
//$s = '{"leads_statuses":[{"id":22410637,"pipeline_id":1434445}]}';
    $arr = json_decode($s, true);
prv($arr);
	$filter = new EventsFilter(); 
	$filter->setTypes(['lead_status_changed'])->setCreatedAt(time()-(60*60*2))->setValueAfter($arr);
	$events = $apiClient->events()->get($filter);	
	return $events;
}
Массивы разные перепробовал - везде одна и та же ошибка. Если я что-то делаю неправильно - подскажите как нужно.

StackTrace: Fatal error: Uncaught AmoCRM\Exceptions\AmoCRMApiException: Invalid http status in /vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php:454 Stack trace: #0 domains/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(505): AmoCRM\Client\AmoCRMApiRequest->checkHttpStatus(Object(GuzzleHttp\Psr7\Response), Array) #1 domains/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(414): AmoCRM\Client\AmoCRMApiRequest->parseResponse(Object(GuzzleHttp\Psr7\Response)) #2 domains/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(89): AmoCRM\Client\AmoCRMApiRequest->get('https://...', Array) #3 /test_invoice.php(17): AmoCRM\EntitiesServices\BaseEntity->get(Object(AmoCRM\Filters\EventsFilter)) #4 ../test_invoice.php(8): GetEvents(Object(Am in vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php on line 454

**Comment by veed007** [comment]
{"leads_statuses":[{"status_id":22410637,"pipeline_id":1434445}]}
так сделал. заработало. виной всему невнимательность.
В документации к Api выглядит это так 
&filter[value_after][leads_statuses][0][pipeline_id]='.$pipline_id.'&filter[value_after][leads_statuses][0][status_id]='.$status_id
