### ISSUE TITLE
Ошибка валидации при обновление сделки

### ISSUE THREAD

**Issue by jury-kapkov** [amocrm/amocrm-api-php#366]
Использую библиотеку версии 0.5.2
При вызове метода updateOne у LeadModel вылетает ошибка валидации полей "Response has validation errors"
Интеграция стабильно работало месяца два, а вот с 13 числа, примерно, некоторые сделки перестали обновляться. Первое на что думал - где-то ошибка в полях, которые обновляю, но затем я взял id "битой" сделки и написал код, который просто получает сделку и сразу пытается обновить - ошибка та же. Перелазил в гугле, посравнивал поля "битой сделки" и той что обновляется. В работающих были поля  [created_by]  и [updated_by] нули. Битой сделке потом задал эти поля в 0 и все стало сохраняться. Вопрос, при каких условиях сделки могут так "ломаться"? 
Сегодня руками в амо создал сделку, заполнил выборочно пару полей, попытался ее обновить кодом и получил ошибку. Пользователи не удалялись, которые были прикреплены к сделкам.

Пробовал менять "битую" сделку просто через апи - меняется, а через библиотеку нет. Сейчас почти все новые сделки не обновляются через библиотеку. 

Прикрепляю сообщение ексепшена.
`AmoCRM\Exceptions\AmoCRMApiErrorResponseException: Response has validation errors in /sites/trimmmoscow.salesup.pro/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php:467 Stack trace: #0 /sites/trimmmoscow.salesup.pro/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(507): AmoCRM\Client\AmoCRMApiRequest->checkHttpStatus(Object(GuzzleHttp\Psr7\Response), Array) #1 /sites/trimmmoscow.salesup.pro/vendor/amocrm/amocrm-api-library/src/AmoCRM/Client/AmoCRMApiRequest.php(262): AmoCRM\Client\AmoCRMApiRequest->parseResponse(Object(GuzzleHttp\Psr7\Response)) #2 /sites/trimmmoscow.salesup.pro/vendor/amocrm/amocrm-api-library/src/AmoCRM/EntitiesServices/BaseEntity.php(251): AmoCRM\Client\AmoCRMApiRequest->patch('api/v4/leads/15...', Array) #3 /sites/trimmmoscow.salesup.pro/app/Services/LeadService.php(86): AmoCRM\EntitiesServices\BaseEntity->updateOne(Object(AmoCRM\Models\LeadModel)) #4 /sites/trimmmoscow.salesup.pro/app/Controllers/TransferController.php(108): Persis\Services\LeadService->updateOne(Object(AmoCRM\Models\LeadModel)) #5 [internal function]: Persis\Controllers\TransferController::confirm(Object(Symfony\Component\HttpFoundation\Request), Array) #6 /sites/trimmmoscow.salesup.pro/app/Core.php(56): call_user_func_array(Array, Array) #7 /sites/trimmmoscow.salesup.pro/api/index.php(27): Persis\Core->handle(Object(Symfony\Component\HttpFoundation\Request))`

**Comment by makeroi** [comment]
@jury-kapkov не видно ошибки самой

Библиотека пытается перезаписать все поля. Такая ошибка возникает (получить и сразу обновить) только если текущее значение поля не может пройти валидацию.

Обрати внимание скорее все проблема отсюда https://github.com/amocrm/amocrm-api-php/issues/224
или https://github.com/amocrm/amocrm-api-php/issues/220
